# Generated by Django 4.1.3 on 2022-11-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidding',
            old_name='startbid',
            new_name='newBid',
        ),
    ]
