# Generated by Django 4.1.3 on 2022-11-22 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creator',
            field=models.ManyToManyField(blank=True, null=True, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
